In [2]:
!python run_nerf.py --config configs/lego.txt --expname lego0917_01 --lrate 0.01 --lrate_decay 10 --i_video 1000 

Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
  0%|                                                  | 0/3000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tenso


 65%|███████████████████████████▉               | 26/40 [07:03<03:47, 16.28s/it]26 16.2643883228302
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 68%|█████████████████████████████              | 27/40 [07:19<03:31, 16.27s/it]27 16.262977123260498
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 70%|██████████████████████████████             | 28/40 [07:35<03:15, 16.27s/it]28 16.262019634246826
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 72%|███████████████████████████████▏           | 29/40 [07:52<02:58, 16.27s/it]29 16.268836498260498
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 75%|████████████████████████████████▎          | 30/40 [08:08<02:42, 16.26s/it]30 16.253164291381836
Lossy conve

[TRAIN] Iter: 1100 Loss: 0.008843417279422283  PSNR: 24.06181526184082          
[TRAIN] Iter: 1200 Loss: 0.009488001465797424  PSNR: 24.068567276000977         
[TRAIN] Iter: 1300 Loss: 0.008608435280621052  PSNR: 24.27570152282715          
[TRAIN] Iter: 1400 Loss: 0.0057754479348659515  PSNR: 26.136999130249023        
[TRAIN] Iter: 1500 Loss: 0.013012290000915527  PSNR: 22.518728256225586         
[TRAIN] Iter: 1600 Loss: 0.006385026965290308  PSNR: 25.78217887878418          
[TRAIN] Iter: 1700 Loss: 0.007184256333857775  PSNR: 25.701059341430664         
[TRAIN] Iter: 1800 Loss: 0.005012063775211573  PSNR: 27.135637283325195         
[TRAIN] Iter: 1900 Loss: 0.007752287667244673  PSNR: 25.340648651123047         
  0%|                                                    | 0/40 [00:00<?, ?it/s]0 0.00107574462890625
torch.Size([400, 400, 3]) torch.Size([400, 400])
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.




 82%|███████████████████████████████████▍       | 33/40 [08:55<01:53, 16.26s/it]33 16.26634168624878
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 85%|████████████████████████████████████▌      | 34/40 [09:11<01:37, 16.25s/it]34 16.24182367324829
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 88%|█████████████████████████████████████▋     | 35/40 [09:28<01:21, 16.25s/it]35 16.25658941268921
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 90%|██████████████████████████████████████▋    | 36/40 [09:44<01:04, 16.25s/it]36 16.2361958026886
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 92%|███████████████████████████████████████▊   | 37/40 [10:00<00:48, 16.25s/it]37 16.247658014297485
Lossy conversi

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 10%|████▍                                       | 4/40 [01:04<09:36, 16.02s/it]4 16.01351022720337
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 12%|█████▌                                      | 5/40 [01:20<09:21, 16.03s/it]5 16.04788899421692
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 15%|██████▌                                     | 6/40 [01:36<09:05, 16.04s/it]6 16.067233085632324
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 18%|███████▋                                    | 7/40 [01:52<08:49, 16.05s/it]7 16.05353331565857
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.



100%|███████████████████████████████████████████| 40/40 [10:42<00:00, 16.06s/it]
Done, saving (40, 400, 400, 3) (40, 400, 400)
test poses shape torch.Size([25, 4, 4])

  0%|                                                    | 0/25 [00:00<?, ?it/s]0 0.0011589527130126953
torch.Size([400, 400, 3]) torch.Size([400, 400])
26.33832601693994

  4%|█▊                                          | 1/25 [00:16<06:41, 16.71s/it]1 16.712204456329346
23.7022268544203

  8%|███▌                                        | 2/25 [00:33<06:24, 16.71s/it]2 16.710399866104126
27.58355046865966

 12%|█████▎                                      | 3/25 [00:50<06:07, 16.71s/it]3 16.701010942459106
26.753409002402016

 16%|███████                                     | 4/25 [01:06<05:50, 16.71s/it]4 16.719703197479248
25.54261398346986

 20%|████████▊                                   | 5/25 [01:23<05:34, 16.72s/it]5 16.730365991592407
26.110930451741595

 24%|██████████▌                                 | 6/25 [0

In [4]:
!python run_nerf.py --config configs/trex.txt --expname trex0918_01 --lrate 0.01 --lrate_decay 10 --i_video 1000 

Loaded image data (378, 504, 3, 55) [378.         504.         416.23374465]
Loaded ./data/llff/trex 14.611281520672364 128.97241851887296
recentered (3, 5)
[[ 1.0000000e+00 -8.9834629e-10 -9.6571471e-09  6.5023249e-09]
 [ 8.9834634e-10  1.0000000e+00  7.2768644e-09 -6.6377899e-09]
 [ 9.6571471e-09 -7.2768644e-09  1.0000000e+00  4.0639531e-10]]
Data:
(55, 3, 5) (55, 378, 504, 3) (55, 2)
HOLDOUT view is 20
Loaded llff (55, 378, 504, 3) (120, 3, 5) [378.      504.      416.23373] ./data/llff/trex
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts []
get rays
done, concats
shuffle rays
done
Begin
TRAIN views are [ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18 19 20 21 22 23 25 26 27
 28 29 30 31 33 34 35 36 37 38 39 41 42 43 44 45 46 47 49 50 51 52 53 54]
TEST views are [ 0  8 16 24 32 40 48]
VAL views are [ 0  8 16 24 32 40 48]
  0%|                                                  | 0/3000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: Us

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 22%|█████████                                 | 26/120 [06:25<23:13, 14.82s/it]26 14.819973468780518
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 22%|█████████▍                                | 27/120 [06:40<22:58, 14.82s/it]27 14.82905387878418
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 23%|█████████▊                                | 28/120 [06:54<22:43, 14.82s/it]28 14.82267141342163
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 24%|██████████▏                               | 29/120 [07:09<22:29, 14.83s/it]29 14.845783233642578
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warn


 52%|█████████████████████▋                    | 62/120 [15:21<14:21, 14.85s/it]62 14.820957899093628
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 52%|██████████████████████                    | 63/120 [15:36<14:05, 14.84s/it]63 14.814941883087158
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 53%|██████████████████████▍                   | 64/120 [15:51<13:50, 14.83s/it]64 14.8164222240448
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 54%|██████████████████████▊                   | 65/120 [16:06<13:35, 14.82s/it]65 14.802818298339844
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 55%|███████████████████████                   | 66/120 [16:21<13:19, 14.81s/it]66 14.790376901626587
Lossy conve

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 82%|██████████████████████████████████▋       | 99/120 [24:30<05:12, 14.86s/it]99 14.886401414871216
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 83%|██████████████████████████████████▏      | 100/120 [24:44<04:57, 14.87s/it]100 14.895910263061523
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 84%|██████████████████████████████████▌      | 101/120 [24:59<04:42, 14.88s/it]101 14.886797428131104
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 85%|██████████████████████████████████▊      | 102/120 [25:14<04:27, 14.88s/it]102 14.88181447982788
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this 

converting to ply format and writing to file took 2.0722079277038574 s
Done, saving mesh at  ./logs/trex0918_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file
[TRAIN] Iter: 1000 Loss: 0.0112220523878932  PSNR: 23.675779342651367           
[TRAIN] Iter: 1100 Loss: 0.010525275021791458  PSNR: 23.591638565063477         
[TRAIN] Iter: 1200 Loss: 0.009509464725852013  PSNR: 23.969478607177734         
[TRAIN] Iter: 1300 Loss: 0.011448850855231285  PSNR: 23.12223243713379          
[TRAIN] Iter: 1400 Loss: 0.008905772119760513  PSNR: 23.914379119873047         
[TRAIN] Iter: 1500 Loss: 0.00801888108253479  PSNR: 24.753686904907227          
[TRAIN] Iter: 1600 Loss: 0.00813706312328577  PSNR: 24.6582088470459            
[TRAIN] Iter: 1700 Loss: 0.007201218046247959  PSNR: 25.22545623779297          
[TRAIN] Iter: 1800 Loss: 0.007779059000313282  PSNR: 24.961633682250977         
[TRAIN] Iter: 1900 Loss: 0.007015170995146036  PSNR: 25.660493850708008  

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 27%|███████████▏                              | 32/120 [07:55<21:52, 14.92s/it]32 14.952001333236694
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 28%|███████████▌                              | 33/120 [08:10<21:38, 14.92s/it]33 14.929198265075684
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 28%|███████████▉                              | 34/120 [08:25<21:24, 14.93s/it]34 14.952686309814453
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 29%|████████████▎                             | 35/120 [08:40<21:09, 14.94s/it]35 14.965780258178711
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this wa


 57%|███████████████████████▊                  | 68/120 [16:54<12:53, 14.87s/it]68 14.85486125946045
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 57%|████████████████████████▏                 | 69/120 [17:09<12:38, 14.87s/it]69 14.857637405395508
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 58%|████████████████████████▌                 | 70/120 [17:23<12:23, 14.86s/it]70 14.850915431976318
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 59%|████████████████████████▊                 | 71/120 [17:38<12:08, 14.86s/it]71 14.856958389282227
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 60%|█████████████████████████▏                | 72/120 [17:53<11:52, 14.85s/it]72 14.834806442260742
Lossy conv

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 88%|███████████████████████████████████▉     | 105/120 [26:05<03:44, 14.94s/it]105 14.93831205368042
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 88%|████████████████████████████████████▏    | 106/120 [26:20<03:29, 14.94s/it]106 14.954209327697754
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 89%|████████████████████████████████████▌    | 107/120 [26:34<03:14, 14.95s/it]107 14.960285186767578
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 90%|████████████████████████████████████▉    | 108/120 [26:49<02:59, 14.95s/it]108 14.94523024559021
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this 

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

  2%|▋                                          | 2/120 [00:29<29:22, 14.94s/it]2 14.933068752288818
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

  2%|█                                          | 3/120 [00:44<29:07, 14.93s/it]3 14.923891544342041
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

  3%|█▍                                         | 4/120 [00:59<28:50, 14.92s/it]4 14.905884981155396
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

  4%|█▊                                         | 5/120 [01:14<28:34, 14.91s/it]5 14.88655948638916
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning


 32%|█████████████▎                            | 38/120 [09:26<20:31, 15.01s/it]38 15.030456304550171
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 32%|█████████████▋                            | 39/120 [09:41<20:17, 15.03s/it]39 15.064456462860107
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 33%|██████████████                            | 40/120 [09:56<20:02, 15.03s/it]40 15.04526138305664
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 34%|██████████████▎                           | 41/120 [10:11<19:48, 15.04s/it]41 15.062150001525879
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 35%|██████████████▋                           | 42/120 [10:26<19:34, 15.06s/it]42 15.08908462524414
Lossy conve

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 62%|██████████████████████████▎               | 75/120 [18:41<11:09, 14.87s/it]75 14.885186195373535
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 63%|██████████████████████████▌               | 76/120 [18:56<10:54, 14.88s/it]76 14.883304357528687
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 64%|██████████████████████████▉               | 77/120 [19:11<10:39, 14.88s/it]77 14.893879652023315
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 65%|███████████████████████████▎              | 78/120 [19:25<10:25, 14.88s/it]78 14.892061948776245
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this wa


 92%|█████████████████████████████████████▉   | 111/120 [27:40<02:15, 15.04s/it]111 15.045143842697144
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 93%|██████████████████████████████████████▎  | 112/120 [27:55<02:00, 15.05s/it]112 15.059598684310913
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 94%|██████████████████████████████████████▌  | 113/120 [28:10<01:45, 15.05s/it]113 15.061004877090454
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 95%|██████████████████████████████████████▉  | 114/120 [28:25<01:30, 15.05s/it]114 15.06223440170288
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 96%|███████████████████████████████████████▎ | 115/120 [28:40<01:15, 15.05s/it]115 15.056878566741943
Lossy

In [5]:
!python run_nerf.py --config configs/horns.txt --expname horns0918_01 --lrate 0.01 --lrate_decay 10 --i_video 1000 

Loaded image data (378, 504, 3, 62) [378.        504.        421.1029647]
Loaded ./data/llff/horns 11.08708448092299 177.40497287419942
recentered (3, 5)
[[ 1.0000000e+00 -7.4366380e-10 -6.9124004e-09 -3.3647782e-09]
 [ 7.4366374e-10  1.0000000e+00 -6.1847794e-09  1.9707988e-08]
 [ 6.9124004e-09  6.1847794e-09  1.0000000e+00 -1.6823891e-09]]
Data:
(62, 3, 5) (62, 378, 504, 3) (62, 2)
HOLDOUT view is 33
Loaded llff (62, 378, 504, 3) (120, 3, 5) [378.      504.      421.10297] ./data/llff/horns
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts []
get rays
done, concats
shuffle rays
done
Begin
TRAIN views are [ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18 19 20 21 22 23 25 26 27
 28 29 30 31 33 34 35 36 37 38 39 41 42 43 44 45 46 47 49 50 51 52 53 54
 55 57 58 59 60 61]
TEST views are [ 0  8 16 24 32 40 48 56]
VAL views are [ 0  8 16 24 32 40 48 56]
  0%|                                                  | 0/3000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torc

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 22%|█████████                                 | 26/120 [06:28<23:22, 14.92s/it]26 14.936196088790894
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 22%|█████████▍                                | 27/120 [06:43<23:08, 14.93s/it]27 14.947843551635742
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 23%|█████████▊                                | 28/120 [06:58<22:54, 14.94s/it]28 14.961016178131104
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 24%|██████████▏                               | 29/120 [07:13<22:39, 14.94s/it]29 14.960345268249512
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this wa


 52%|█████████████████████▋                    | 62/120 [15:28<14:27, 14.95s/it]62 14.934044361114502
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 52%|██████████████████████                    | 63/120 [15:43<14:11, 14.94s/it]63 14.922760009765625
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 53%|██████████████████████▍                   | 64/120 [15:58<13:56, 14.93s/it]64 14.915504217147827
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 54%|██████████████████████▊                   | 65/120 [16:13<13:41, 14.93s/it]65 14.914944171905518
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 55%|███████████████████████                   | 66/120 [16:28<13:25, 14.92s/it]66 14.914878845214844
Lossy con

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 82%|██████████████████████████████████▋       | 99/120 [24:39<05:14, 14.97s/it]99 14.971461057662964
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 83%|██████████████████████████████████▏      | 100/120 [24:54<04:59, 14.97s/it]100 14.973108768463135
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 84%|██████████████████████████████████▌      | 101/120 [25:09<04:44, 14.97s/it]101 14.982289791107178
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 85%|██████████████████████████████████▊      | 102/120 [25:24<04:29, 14.98s/it]102 14.981624841690063
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this

converting to ply format and writing to file took 15.246239185333252 s
saving mesh to ./logs/horns0918_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_20.ply
converting to ply format and writing to file took 3.6660726070404053 s
Done, saving mesh at  ./logs/horns0918_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file
[TRAIN] Iter: 1000 Loss: 0.01261271070688963  PSNR: 22.873123168945312          
[TRAIN] Iter: 1100 Loss: 0.010213748551905155  PSNR: 23.416763305664062         
[TRAIN] Iter: 1200 Loss: 0.010769533924758434  PSNR: 23.153179168701172         
[TRAIN] Iter: 1300 Loss: 0.007147461175918579  PSNR: 25.19680404663086          
[TRAIN] Iter: 1400 Loss: 0.007782928645610809  PSNR: 24.654870986938477         
[TRAIN] Iter: 1500 Loss: 0.009115612134337425  PSNR: 24.000429153442383         
[TRAIN] Iter: 1600 Loss: 0.008863089606165886  PSNR: 24.50735092163086          
[TRAIN] Iter: 1700 L

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 26%|██████████▊                               | 31/120 [07:40<22:04, 14.88s/it]31 14.904505014419556
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 27%|███████████▏                              | 32/120 [07:55<21:50, 14.89s/it]32 14.914981365203857
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 28%|███████████▌                              | 33/120 [08:09<21:36, 14.90s/it]33 14.922065258026123
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 28%|███████████▉                              | 34/120 [08:24<21:22, 14.91s/it]34 14.926367998123169
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this wa


 56%|███████████████████████▍                  | 67/120 [16:36<13:04, 14.81s/it]67 14.795890808105469
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 57%|███████████████████████▊                  | 68/120 [16:50<12:49, 14.80s/it]68 14.780705213546753
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 57%|████████████████████████▏                 | 69/120 [17:05<12:34, 14.80s/it]69 14.796899557113647
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 58%|████████████████████████▌                 | 70/120 [17:20<12:20, 14.80s/it]70 14.80263090133667
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 59%|████████████████████████▊                 | 71/120 [17:35<12:05, 14.80s/it]71 14.801302194595337
Lossy conv

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 87%|███████████████████████████████████▌     | 104/120 [25:44<03:57, 14.87s/it]104 14.878620386123657
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 88%|███████████████████████████████████▉     | 105/120 [25:59<03:43, 14.87s/it]105 14.869149208068848
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 88%|████████████████████████████████████▏    | 106/120 [26:14<03:28, 14.87s/it]106 14.882380723953247
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 89%|████████████████████████████████████▌    | 107/120 [26:29<03:13, 14.87s/it]107 14.872040510177612
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress thi

[TRAIN] Iter: 2900 Loss: 0.0064690001308918  PSNR: 26.350704193115234           
  0%|                                                   | 0/120 [00:00<?, ?it/s]0 0.0009059906005859375
torch.Size([378, 504, 3]) torch.Size([378, 504])
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

  1%|▎                                          | 1/120 [00:14<29:25, 14.84s/it]1 14.84024429321289
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

  2%|▋                                          | 2/120 [00:29<29:10, 14.83s/it]2 14.828684329986572
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

  2%|█                                          | 3/120 [00:44<28:54, 14.83s/it]3 14.81735897064209
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress 


 30%|████████████▌                             | 36/120 [08:54<20:53, 14.92s/it]36 14.9432532787323
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 31%|████████████▉                             | 37/120 [09:09<20:38, 14.92s/it]37 14.9185791015625
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 32%|█████████████▎                            | 38/120 [09:24<20:24, 14.93s/it]38 14.951483488082886
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 32%|█████████████▋                            | 39/120 [09:39<20:09, 14.93s/it]39 14.924013376235962
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 33%|██████████████                            | 40/120 [09:54<19:54, 14.93s/it]40 14.94695782661438
Lossy conversi


 61%|█████████████████████████▌                | 73/120 [18:04<11:35, 14.79s/it]73 14.801135301589966
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 62%|█████████████████████████▉                | 74/120 [18:19<11:20, 14.79s/it]74 14.796842813491821
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 62%|██████████████████████████▎               | 75/120 [18:34<11:05, 14.80s/it]75 14.806525230407715
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 63%|██████████████████████████▌               | 76/120 [18:49<10:51, 14.80s/it]76 14.798089742660522
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 64%|██████████████████████████▉               | 77/120 [19:04<10:36, 14.80s/it]77 14.808449268341064
Lossy con

Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 92%|█████████████████████████████████████▌   | 110/120 [27:13<02:28, 14.87s/it]110 14.864789724349976
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 92%|█████████████████████████████████████▉   | 111/120 [27:28<02:13, 14.87s/it]111 14.86023736000061
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 93%|██████████████████████████████████████▎  | 112/120 [27:43<01:59, 14.88s/it]112 14.896671772003174
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 94%|██████████████████████████████████████▌  | 113/120 [27:58<01:44, 14.88s/it]113 14.885557174682617
Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this

In [20]:
!python run_nerf.py --config configs/fern.txt --expname fern_metrictest --render_only --render_test

Loaded image data (378, 504, 3, 20) [378.         504.         407.56579161]
Loaded ./data/llff/fern 16.985296178676084 80.00209740336334
recentered (3, 5)
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  1.4901161e-09]
 [ 0.0000000e+00  1.0000000e+00 -1.8730975e-09 -9.6857544e-09]
 [-0.0000000e+00  1.8730975e-09  1.0000000e+00  0.0000000e+00]]
Data:
(20, 3, 5) (20, 378, 504, 3) (20, 2)
HOLDOUT view is 12
Loaded llff (20, 378, 504, 3) (120, 3, 5) [378.     504.     407.5658] ./data/llff/fern
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['./logs/fern_metrictest_hashXYZ_sphereVIEW_fine512_log2T19_lr0.0005_decay250_RAdam_sparse1e-10_TV1e-06/001000.tar']
Reloading from ./logs/fern_metrictest_hashXYZ_sphereVIEW_fine512_log2T19_lr0.0005_decay250_RAdam_sparse1e-10_TV1e-06/001000.tar
RENDER ONLY
test poses shape torch.Size([3, 3, 4])
  0%|                                                     | 0/3 [00:00<?, ?it/s]0 0.0014181137084960938
/opt/conda/lib/python3.9/site-packages

In [ ]:
    parser.add_argument("--n_iters", type=int, default=1000,
                        help='layers in network')
    parser.add_argument("--i_print",   type=int, default=100,
                        help='frequency of console printout and metric loggin')
    parser.add_argument("--i_img",     type=int, default=1000,
                        help='frequency of tensorboard image logging')
    parser.add_argument("--i_weights", type=int, default=1000,
                        help='frequency of weight ckpt saving')
    parser.add_argument("--i_testset", type=int, default=1000,
                        help='frequency of testset saving')
    parser.add_argument("--i_video",   type=int, default=1000,
                        help='frequency of render_poses video saving')
    parser.add_argument("--i_mesh", type=int, default=1000,
                        help='frequency of mesh saving')