In [20]:
!python run_nerf.py --config configs/fern.txt --expname fern_metrictest --render_only --render_test

Loaded image data (378, 504, 3, 20) [378.         504.         407.56579161]
Loaded ./data/llff/fern 16.985296178676084 80.00209740336334
recentered (3, 5)
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  1.4901161e-09]
 [ 0.0000000e+00  1.0000000e+00 -1.8730975e-09 -9.6857544e-09]
 [-0.0000000e+00  1.8730975e-09  1.0000000e+00  0.0000000e+00]]
Data:
(20, 3, 5) (20, 378, 504, 3) (20, 2)
HOLDOUT view is 12
Loaded llff (20, 378, 504, 3) (120, 3, 5) [378.     504.     407.5658] ./data/llff/fern
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts ['./logs/fern_metrictest_hashXYZ_sphereVIEW_fine512_log2T19_lr0.0005_decay250_RAdam_sparse1e-10_TV1e-06/001000.tar']
Reloading from ./logs/fern_metrictest_hashXYZ_sphereVIEW_fine512_log2T19_lr0.0005_decay250_RAdam_sparse1e-10_TV1e-06/001000.tar
RENDER ONLY
test poses shape torch.Size([3, 3, 4])
  0%|                                                     | 0/3 [00:00<?, ?it/s]0 0.0014181137084960938
/opt/conda/lib/python3.9/site-packages

In [24]:
!python run_nerf.py --config configs/lego.txt --expname lego0920_01 --lrate 0.01 --lrate_decay 10

Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
  0%|                                                  | 0/1000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tenso

Retrieving densities at grid points: 100%|████| 512/512 [00:12<00:00, 41.63it/s]
./logs/lego0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_999_5.ply
saving mesh to ./logs/lego0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_999_5.ply
Removing noise ...
Mesh has 0.34 M vertices and 0.69 M faces.
cool!  saving clusted mesh to ./logs/lego0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_999_5.ply
converting to ply format and writing to file took 10.164893865585327 s
./logs/lego0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_999_10.ply
saving mesh to ./logs/lego0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_999_10.ply
Removing noise ...
Mesh has 0.25 M vertices and 0.51 M faces.
cool!  saving clusted mesh to ./logs/

Mesh has 0.04 M vertices and 0.09 M faces.
cool!  saving clusted mesh to ./logs/lego0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_999_20.ply
converting to ply format and writing to file took 2.328115224838257 s
Done, saving mesh at  ./logs/lego0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file
[TRAIN] Iter: 1000 Loss: 0.00696014566347003  PSNR: 25.785554885864258          
100%|███████████████████████████████████████| 1000/1000 [24:22<00:00,  1.46s/it]


In [3]:
!python run_nerf.py --config configs/ship.txt --expname ship0920_01 --lrate 0.01 --lrate_decay 10

Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 555.5555155968841] ./data/nerf_synthetic/ship
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
  0%|                                                  | 0/1000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tenso

Retrieving densities at grid points: 100%|████| 512/512 [00:11<00:00, 43.33it/s]
./logs/ship0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
saving mesh to ./logs/ship0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
Removing noise ...
Mesh has 0.63 M vertices and 1.27 M faces.
cool!  saving clusted mesh to ./logs/ship0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
converting to ply format and writing to file took 16.505478620529175 s
./logs/ship0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_10.ply
saving mesh to ./logs/ship0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_10.ply
Removing noise ...
Mesh has 0.45 M vertices and 0.91 M faces.
cool!  saving clusted mesh to ./

converting to ply format and writing to file took 1.003326177597046 s
Done, saving mesh at  ./logs/ship0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file Time : 
[TRAIN] Iter: 1000 Loss: 0.015764988958835602  PSNR: 21.510560989379883
100%|███████████████████████████████████████| 1000/1000 [24:40<00:00,  1.48s/it]


In [4]:
!python run_nerf.py --config configs/drums.txt --expname drums0920_01 --lrate 0.01 --lrate_decay 10

Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 625.0000252084244] ./data/nerf_synthetic/drums
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
  0%|                                                  | 0/1000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tens

Retrieving densities at grid points: 100%|████| 512/512 [00:11<00:00, 43.38it/s]
./logs/drums0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
saving mesh to ./logs/drums0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
Removing noise ...
Mesh has 0.16 M vertices and 0.32 M faces.
cool!  saving clusted mesh to ./logs/drums0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
converting to ply format and writing to file took 6.8698108196258545 s
./logs/drums0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_10.ply
saving mesh to ./logs/drums0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_10.ply
Removing noise ...
Mesh has 0.09 M vertices and 0.18 M faces.
cool!  saving clusted mesh 

converting to ply format and writing to file took 2.100045919418335 s
Done, saving mesh at  ./logs/drums0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file Time : 
[TRAIN] Iter: 1000 Loss: 0.014100360684096813  PSNR: 22.576438903808594         
100%|███████████████████████████████████████| 1000/1000 [24:11<00:00,  1.45s/it]


In [5]:
!python run_nerf.py --config configs/fern.txt --expname fern0920_01 --lrate 0.01 --lrate_decay 10

Loaded image data (378, 504, 3, 20) [378.         504.         407.56579161]
Loaded ./data/llff/fern 16.985296178676084 80.00209740336334
recentered (3, 5)
[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  1.4901161e-09]
 [ 0.0000000e+00  1.0000000e+00 -1.8730975e-09 -9.6857544e-09]
 [-0.0000000e+00  1.8730975e-09  1.0000000e+00  0.0000000e+00]]
Data:
(20, 3, 5) (20, 378, 504, 3) (20, 2)
HOLDOUT view is 12
Loaded llff (20, 378, 504, 3) (120, 3, 5) [378.     504.     407.5658] ./data/llff/fern
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts []
get rays
done, concats
shuffle rays
done
Begin
TRAIN views are [ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18 19]
TEST views are [ 0  8 16]
VAL views are [ 0  8 16]
  0%|                                                  | 0/1000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internall


 23%|█████████▊                                | 28/120 [06:48<22:20, 14.57s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 24%|██████████▏                               | 29/120 [07:03<22:06, 14.57s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 25%|██████████▌                               | 30/120 [07:17<21:50, 14.56s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 26%|██████████▊                               | 31/120 [07:32<21:36, 14.57s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 27%|███████████▏                              | 32/120 [07:46<21:21, 14.56s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.


 90%|████████████████████████████████████▉    | 108/120 [26:14<02:54, 14.57s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 91%|█████████████████████████████████████▏   | 109/120 [26:28<02:40, 14.57s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 92%|█████████████████████████████████████▌   | 110/120 [26:43<02:25, 14.57s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 92%|█████████████████████████████████████▉   | 111/120 [26:58<02:11, 14.57s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 93%|██████████████████████████████████████▎  | 112/120 [27:12<01:56, 14.58s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.



In [6]:
!python run_nerf.py --config configs/trex.txt --expname trex0920_01 --lrate 0.01 --lrate_decay 10

Loaded image data (378, 504, 3, 55) [378.         504.         416.23374465]
Loaded ./data/llff/trex 14.611281520672364 128.97241851887296
recentered (3, 5)
[[ 1.0000000e+00 -8.9834629e-10 -9.6571471e-09  6.5023249e-09]
 [ 8.9834634e-10  1.0000000e+00  7.2768644e-09 -6.6377899e-09]
 [ 9.6571471e-09 -7.2768644e-09  1.0000000e+00  4.0639531e-10]]
Data:
(55, 3, 5) (55, 378, 504, 3) (55, 2)
HOLDOUT view is 20
Loaded llff (55, 378, 504, 3) (120, 3, 5) [378.      504.      416.23373] ./data/llff/trex
Auto LLFF holdout, 8
DEFINING BOUNDS
NEAR FAR 0.0 1.0
Found ckpts []
get rays
done, concats
shuffle rays
done
Begin
TRAIN views are [ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18 19 20 21 22 23 25 26 27
 28 29 30 31 33 34 35 36 37 38 39 41 42 43 44 45 46 47 49 50 51 52 53 54]
TEST views are [ 0  8 16 24 32 40 48]
VAL views are [ 0  8 16 24 32 40 48]
  0%|                                                  | 0/1000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: Us

 56%|███████████████████████▍                  | 67/120 [16:13<12:47, 14.49s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 57%|███████████████████████▊                  | 68/120 [16:27<12:33, 14.48s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 57%|████████████████████████▏                 | 69/120 [16:41<12:18, 14.48s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 58%|████████████████████████▌                 | 70/120 [16:56<12:03, 14.47s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 59%|████████████████████████▊                 | 71/120 [17:10<11:48, 14.47s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.



Retrieving densities at grid points: 100%|████| 512/512 [00:12<00:00, 42.63it/s]
./logs/trex0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
saving mesh to ./logs/trex0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
Removing noise ...
Mesh has 2.46 M vertices and 5.12 M faces.
cool!  saving clusted mesh to ./logs/trex0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
converting to ply format and writing to file took 83.4737720489502 s
./logs/trex0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_10.ply
saving mesh to ./logs/trex0920_01_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_10.ply
Removing noise ...
Mesh has 1.01 M vertices and 2.08 M faces.
cool!  saving clusted mesh to ./lo

## 개선

In [11]:
!python run_nerf.py --config configs/lego.txt --expname lego0920_03 --lrate 0.01 --lrate_decay 100 --netwidth 128

Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
  0%|                                                  | 0/1000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tenso

Retrieving densities at grid points: 100%|████| 512/512 [00:12<00:00, 42.32it/s]
./logs/lego0920_03_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay100_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
saving mesh to ./logs/lego0920_03_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay100_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
Removing noise ...
Mesh has 0.39 M vertices and 0.79 M faces.
cool!  saving clusted mesh to ./logs/lego0920_03_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay100_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_5.ply
converting to ply format and writing to file took 10.950244665145874 s
./logs/lego0920_03_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay100_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_10.ply
saving mesh to ./logs/lego0920_03_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay100_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_1000_10.ply
Removing noise ...
Mesh has 0.29 M vertices and 0.59 M faces.
cool!  saving clusted mesh 

converting to ply format and writing to file took 2.780935049057007 s
Done, saving mesh at  ./logs/lego0920_03_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay100_RAdam_sparse1e-10_TV1e-06/mash_file Time : 
[TRAIN] Iter: 1000 Loss: 0.006792630068957806  PSNR: 25.959163665771484         
100%|███████████████████████████████████████| 1000/1000 [24:34<00:00,  1.47s/it]


In [15]:
!python run_nerf.py --config configs/lego.txt --expname lego0920_05 --lrate 0.01 --lrate_decay 10 

Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
  0%|                                                  | 0/2000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2157.)
  return _VF.meshgrid(tenso

Retrieving densities at grid points: 100%|████| 512/512 [00:11<00:00, 42.95it/s]
./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_5.ply
saving mesh to ./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_5.ply
Removing noise ...
Mesh has 0.31 M vertices and 0.62 M faces.
cool!  saving clusted mesh to ./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_5.ply
converting to ply format and writing to file took 8.577819108963013 s
./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_10.ply
saving mesh to ./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_10.ply


Removing noise ...
Mesh has 0.30 M vertices and 0.62 M faces.
cool!  saving clusted mesh to ./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_10.ply
converting to ply format and writing to file took 8.295019388198853 s
./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_20.ply
saving mesh to ./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_20.ply
Removing noise ...
Mesh has 0.30 M vertices and 0.61 M faces.
cool!  saving clusted mesh to ./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_2000_20.ply
converting to ply format and writing to file took 7.572704553604126 s
Done, saving mesh at  ./logs/lego0920_05_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file Time : 
[TRAIN] Iter: 2000

In [16]:
!python run_nerf.py --config configs/lego.txt --expname lego0921 --lrate 0.01 --lrate_decay 10  --render_only --render_test

Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
TEST views are [113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130
 131 132 133 134 135 136 137]
VAL views are [100 101 102 103 104 105 106 107 108 109 110 111 112]
  0%|                                                  | 0/3000 [00:00<?, ?it/s][Config] Center cropping of size 200 x 200 is enabled until iter 500
/aiffel/aiffel/Aifflethon/Volumetric/radam.py:58: UserWarning: This overload of addcmul_ is deprecated:
	addcmul_(Number value, Tensor tensor1, Tensor tensor2)
Consider using one of the following sig


 55%|███████████████████████▋                   | 22/40 [05:51<04:46, 15.91s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 57%|████████████████████████▋                  | 23/40 [06:06<04:30, 15.91s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 60%|█████████████████████████▊                 | 24/40 [06:22<04:14, 15.92s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 62%|██████████████████████████▉                | 25/40 [06:38<03:58, 15.92s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 65%|███████████████████████████▉               | 26/40 [06:54<03:43, 15.94s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.


In [41]:
!python run_nerf.py --config configs/lego.txt --expname lego0921 --lrate 0.01 --lrate_decay 10  --render_only --render_test

Loaded blender (138, 400, 400, 4) torch.Size([40, 4, 4]) [400, 400, 555.5555155968841] ./data/nerf_synthetic/lego
Found ckpts ['./logs/lego0921_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/003000.tar']
Reloading from ./logs/lego0921_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/003000.tar
Not ndc!
RENDER ONLY
test poses shape torch.Size([25, 4, 4])
  0%|                                                    | 0/25 [00:00<?, ?it/s]torch.Size([400, 400, 3]) torch.Size([400, 400])
/opt/conda/lib/python3.9/site-packages/skimage/metrics/_structural_similarity.py:107: UserWarning: Inputs have mismatched dtype.  Setting data_range based on im1.dtype.
  ch_result = structural_similarity(im1[..., ch],
26.198684414080738 0.9296014035980157 0.08769986033439636
100%|███████████████████████████████████████████| 25/25 [06:57<00:00, 16.69s/it]
render_time 417.155957698822
Avg PSNR over Test set:  25.9997914482703
Avg SSIM over Test set:  0.924

## 우쿨렐레 

In [1]:
!python run_nerf.py --config configs/ukulele.txt --expname ukulele_blur --datadir ./data/ingp/ukulele_blur --lrate 0.01 --lrate_decay 10 --factor 2

Matplotlib is building the font cache; this may take a moment.
Data:
(72, 4, 4) (72, 540, 540, 3)
HOLDOUT view is 5
bounding_box_llff (tensor([-505.3726, -865.0451,   -1.0001]), tensor([3.8454e+04, 5.3033e+02, 1.0001e+00]))
bounding_box_blender (tensor([-4.6714, -4.8135, -4.2141]), tensor([4.3427, 3.8432, 3.2838]))
Loaded ingp (72, 540, 540, 3) torch.Size([40, 4, 4]) [540, 540, 674.091477002966] ./data/ingp/ukulele_blur
Auto LLFF/ingp holdout, 8
Found ckpts []
Not ndc!
Begin
TRAIN views are [ 1  2  3  4  5  6  7  9 10 11 12 13 14 15 17 18 19 20 21 22 23 25 26 27
 28 29 30 31 33 34 35 36 37 38 39 41 42 43 44 45 46 47 49 50 51 52 53 54
 55 57 58 59 60 61 62 63 65 66 67 68 69 70 71]
TEST views are [ 0  8 16 24 32 40 48 56 64]
VAL views are [ 0  8 16 24 32 40 48 56 64]
  0%|                                                  | 0/3000 [00:00<?, ?it/s]/opt/conda/lib/python3.9/site-packages/torch/functional.py:445: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass


 50%|█████████████████████▌                     | 20/40 [09:48<09:48, 29.44s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 52%|██████████████████████▌                    | 21/40 [10:17<09:19, 29.44s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 55%|███████████████████████▋                   | 22/40 [10:47<08:50, 29.45s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 57%|████████████████████████▋                  | 23/40 [11:16<08:20, 29.46s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.

 60%|█████████████████████████▊                 | 24/40 [11:46<07:51, 29.46s/it]Lossy conversion from float32 to uint8. Range [0, 1]. Convert image to uint8 prior to saving to suppress this warning.


 95%|██████████████████████████████████████  | 222M/233M [00:03<00:00, 70.1MB/s]

100%|████████████████████████████████████████| 233M/233M [00:03<00:00, 69.8MB/s]
Downloading: "https://raw.githubusercontent.com/richzhang/PerceptualSimilarity/master/lpips/weights/v0.1/alex.pth" to /aiffel/.cache/torch/hub/checkpoints/alex.pth


100%|██████████████████████████████████████| 5.87k/5.87k [00:00<00:00, 3.66MB/s]
PSNR : 21.6419 SSIM : 0.8558 LPIPS : 0.31789

 11%|█████                                        | 1/9 [00:34<04:33, 34.13s/it]PSNR : 17.4977 SSIM : 0.7536 LPIPS : 0.46195

 22%|██████████                                   | 2/9 [01:04<03:42, 31.83s/it]PSNR : 17.8033 SSIM : 0.7502 LPIPS : 0.50157

 33%|███████████████                              | 3/9 [01:34<03:06, 31.08s/it]PSNR : 17.5554 SSIM : 0.7317 LPIPS : 0.48812

 44%|████████████████████                         | 4/9 [02:04<02:33, 30.74s/it]PSNR : 18.1249 SSIM : 0.7422 LPIPS : 0.48564

 56%|█████████████████████████          

Retrieving densities at grid points: 100%|████| 512/512 [00:12<00:00, 42.12it/s]
./logs/ukulele_blur_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_3000_5.ply
saving mesh to ./logs/ukulele_blur_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_3000_5.ply
Removing noise ...
Mesh has 0.09 M vertices and 0.19 M faces.
cool!  saving clusted mesh to ./logs/ukulele_blur_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_3000_5.ply
converting to ply format and writing to file took 8.041666746139526 s
./logs/ukulele_blur_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_3000_10.ply
saving mesh to ./logs/ukulele_blur_hashXYZ_sphereVIEW_fine512_log2T19_lr0.01_decay10_RAdam_sparse1e-10_TV1e-06/mash_file/test_mesh_3000_10.ply
Removing noise ...
Mesh has 0.03 M vertices and 0.06 M faces.
cool!  saving clusted mesh t

In [ ]:
!python run_nerf.py --config configs/ukulele.txt --expname ukulele --lrate 0.01 --lrate_decay 10 --factor 2

ffmpeg version 4.2.7-0ubuntu0.1 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.4.0-1ubuntu1~20.04.1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --e

Processed file [28/72]
  Name:            0029.jpg
  Dimensions:      1080 x 1080
  Camera:          #1 - OPENCV
  Focal Length:    1296.00px
  Features:        1318
Processed file [29/72]
  Name:            0028.jpg
  Dimensions:      1080 x 1080
  Camera:          #1 - OPENCV
  Focal Length:    1296.00px
  Features:        2680
Processed file [30/72]
  Name:            0030.jpg
  Dimensions:      1080 x 1080
  Camera:          #1 - OPENCV
  Focal Length:    1296.00px
  Features:        1897
Processed file [31/72]
  Name:            0031.jpg
  Dimensions:      1080 x 1080
  Camera:          #1 - OPENCV
  Focal Length:    1296.00px
  Features:        2109
Processed file [32/72]
  Name:            0032.jpg
  Dimensions:      1080 x 1080
  Camera:          #1 - OPENCV
  Focal Length:    1296.00px
  Features:        2072
Processed file [33/72]
  Name:            0033.jpg
  Dimensions:      1080 x 1080
  Camera:          #1 - OPENCV
  Focal Length:    1296.00px
  Features:        2572
Proc